export type AppState = 'loading' | 'form' | 'chart_ready' | 'report_streaming' | 'report_ready' | 'question_streaming' | 'error'
export interface Location { code: string; parent_code: string; name: string; level: 'province' | 'city' }
export interface PublicMetadata { name: string; slug: string; daily_limit: number; ttl_hours: number; max_questions: number; locations: Location[]; quota: { remaining: number; resets_at: string } }
export interface BirthPayload { name: string | null; gender: 'male' | 'female'; birth_date: string; birth_time: string | null; birth_time_unknown: boolean; province_code: string; city_code: string; true_solar_time: boolean; focus_topics: string[] }
export interface Pillar { stem: string; branch: string; ganZhi: string; stemTenGod: string; hiddenStems: Array<{ stem: string; tenGod: string; isMain: boolean }> }
export interface FortuneChart { input: BirthPayload; calculation_policy: Record<string, unknown>; pillars: { year: Pillar; month: Pillar; day: Pillar; hour: Pillar | null }; day_master: { char: string; element: string; polarity: string }; five_elements: Record<string, number>; ten_gods: Record<string, string>; hidden_stems: Record<string, unknown[]>; da_yun: { isForward: boolean; startAge: number; cycles: Array<{ ganZhi: string; startAge: number; endAge: number; stemTenGod: string }> }; interactions: Array<{ description: string }>; solar_time: { trueSolarTime: string } | null; attribution: { name: string; url: string } }
export interface PublicMessage { id: string; role: 'user' | 'assistant'; content: string; created_at: string }
export interface SessionPayload { session: { id: string; status: string; expires_at: string; remaining_questions: number }; quota?: { daily_limit: number; remaining: number; resets_at: string }; chart: FortuneChart; messages: PublicMessage[] }
export interface SseEvent { type: string; data: { content?: string; code?: string; message?: string } }
