<script setup lang="ts">
import { ArrowLeft, Bot, Boxes, FileText, Save, Wrench } from 'lucide-vue-next'
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '@/api/client'
import type { Agent, ModelConfig, Skill, Tool } from '@/types'
const route=useRoute(),router=useRouter(),id=computed(()=>route.params.id as string|undefined),active=ref('basic'),models=ref<ModelConfig[]>([]),tools=ref<Tool[]>([]),skills=ref<Skill[]>([]),prompt=ref('# 系统提示词\n\n请描述这个智能体的职责、行为边界与输出要求。'),error=ref(''),saving=ref(false)
const form=reactive({name:'',description:'',model_id:'',tool_ids:[] as string[],skill_ids:[] as string[],work_directory:'',enabled:true})
const tabs=[{id:'basic',label:'基本信息',icon:Bot},{id:'prompt',label:'系统提示词',icon:FileText},{id:'tools',label:'工具选择',icon:Wrench},{id:'skills',label:'技能选择',icon:Boxes}]
function toggle(list:string[],value:string){const at=list.indexOf(value);at>=0?list.splice(at,1):list.push(value)}
async function load(){try{[models.value,tools.value,skills.value]=await Promise.all([api<ModelConfig[]>('/api/models'),api<Tool[]>('/api/tools'),api<Skill[]>('/api/skills')]);if(id.value){const [agent,p]=await Promise.all([api<Agent>(`/api/agents/${id.value}`),api<{content:string}>(`/api/agents/${id.value}/prompt`)]);Object.assign(form,agent);prompt.value=p.content}else form.model_id=models.value[0]?.id||''}catch(e){error.value=(e as Error).message}}
async function save(){saving.value=true;error.value='';try{const agent=await api<Agent>(id.value?`/api/agents/${id.value}`:'/api/agents',{method:id.value?'PUT':'POST',body:JSON.stringify(form)});await api(`/api/agents/${agent.id}/prompt`,{method:'PUT',body:JSON.stringify({content:prompt.value})});await router.push('/agents')}catch(e){error.value=(e as Error).message}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page-heading"><div><RouterLink class="back-link" to="/agents"><ArrowLeft :size="13"/>返回智能体</RouterLink><h1>{{id?'编辑智能体':'新建智能体'}}</h1><p class="subtitle">配置模型、系统提示词和可调用能力。</p></div><button class="button" :disabled="saving" @click="save"><Save :size="14"/>{{saving?'保存中...':'保存智能体'}}</button></div><div v-if="error" class="error">{{error}}</div><div class="editor-shell"><div class="tabs"><button v-for="tab in tabs" :key="tab.id" class="tab" :class="{active:active===tab.id}" @click="active=tab.id"><component :is="tab.icon" :size="14"/>{{tab.label}}</button></div><section v-if="active==='basic'" class="editor-section"><div class="section-heading"><h2>基本信息</h2><p>名称、说明和运行环境。</p></div><div class="form-grid"><div class="field"><label>名称</label><input v-model="form.name" required placeholder="例如：研发助手"></div><div class="field"><label>模型</label><select v-model="form.model_id"><option v-for="model in models" :key="model.id" :value="model.id">{{model.name}} · {{model.model}}</option></select></div><div class="field field--full"><label>描述</label><textarea v-model="form.description" placeholder="说明这个智能体适合处理什么任务"></textarea></div><div class="field field--full"><label>独立工作目录</label><input v-model="form.work_directory" placeholder="留空将使用 workspace/runtime/<agent-id>"><div class="field-help">读写文件与命令执行都会限制在该目录内。</div></div><div class="field field--full checkline"><input id="agent-enabled" v-model="form.enabled" type="checkbox"><label for="agent-enabled">允许运行此智能体</label></div></div></section><section v-if="active==='prompt'" class="editor-section prompt-section"><div class="section-heading"><h2>系统提示词</h2><p>内容保存到该智能体独立的 agent.md。</p></div><textarea v-model="prompt" class="prompt-editor" spellcheck="false"/></section><section v-if="active==='tools'" class="editor-section"><div class="section-heading"><h2>工具选择</h2><p>只有全局启用且在此选中的工具才会暴露给模型。</p></div><div class="selector-list"><label v-for="tool in tools" :key="tool.id" :class="{disabled:!tool.enabled}"><input type="checkbox" :checked="form.tool_ids.includes(tool.id)" :disabled="!tool.enabled" @change="toggle(form.tool_ids,tool.id)"><span><b>{{tool.name}}</b><small>{{tool.description}}</small></span><em :class="tool.approval_required?'warn':'ok'">{{tool.approval_required?'每次审批':'自动执行'}}</em></label></div></section><section v-if="active==='skills'" class="editor-section"><div class="section-heading"><h2>技能选择</h2><p>运行时将选中技能的 SKILL.md 注入上下文。</p></div><div class="selector-list"><label v-for="skill in skills" :key="skill.id" :class="{disabled:!skill.enabled}"><input type="checkbox" :checked="form.skill_ids.includes(skill.id)" :disabled="!skill.enabled" @change="toggle(form.skill_ids,skill.id)"><span><b>{{skill.name}}</b><small>{{skill.description||'暂无描述'}}</small></span><em :class="skill.enabled?'ok':'warn'">{{skill.enabled?'可用':'已停用'}}</em></label><div v-if="!skills.length" class="empty"><div><Boxes/><h2>没有可选技能</h2><p>请先到技能页面创建或导入。</p></div></div></div></section></div></template>
<style scoped>.back-link{display:inline-flex;align-items:center;gap:5px;color:var(--muted);font-size:11px;text-decoration:none}.editor-shell{border:1px solid var(--line);background:white;border-radius:var(--radius)}.editor-shell .tabs{padding:0 16px;margin:0}.tab{display:flex;align-items:center;gap:7px}.editor-section{display:grid;grid-template-columns:210px minmax(0,1fr);gap:28px;padding:25px}.section-heading h2{font-size:14px;margin:0 0 5px}.section-heading p{font-size:10px;color:var(--muted);line-height:1.6;margin:0}.prompt-section{align-items:start}.prompt-editor{width:100%;min-height:440px;resize:vertical;border:1px solid var(--line-dark);background:#202622;color:#e6ede8;border-radius:4px;padding:16px;font:11px/1.75 ui-monospace,monospace}.selector-list{display:grid;gap:7px}.selector-list>label{min-height:64px;display:grid;grid-template-columns:18px 1fr auto;align-items:center;gap:10px;border:1px solid var(--line);padding:10px 12px;cursor:pointer}.selector-list>label:hover{background:#f8faf7}.selector-list>label.disabled{opacity:.5;cursor:not-allowed}.selector-list b,.selector-list small{display:block}.selector-list b{font-size:12px}.selector-list small{font-size:10px;color:var(--muted);margin-top:3px}.selector-list em{font-style:normal;font-size:9px;padding:4px 6px}.selector-list em.ok{background:#e4f2cc;color:#405b1a}.selector-list em.warn{background:#fff0d2;color:#81550d}@media(max-width:760px){.editor-section{grid-template-columns:1fr;gap:16px;padding:18px}.prompt-editor{min-height:340px}}
</style>
