<script setup lang="ts">
import { CheckCircle2, Pencil, Plus, RefreshCw, Trash2, X } from 'lucide-vue-next'
import { onMounted, reactive, ref } from 'vue'
import { api } from '@/api/client'
import type { ModelConfig } from '@/types'

const items = ref<ModelConfig[]>([]), loading = ref(false), error = ref(''), message = ref(''), editing = ref<ModelConfig | null>(null), showForm = ref(false)
const form = reactive({ name: '', provider: 'deepseek' as 'deepseek'|'qwen', model: 'deepseek-chat', base_url: 'https://api.deepseek.com', api_key: '', enabled: true, temperature: 0.7, max_tokens: 4096 })
async function load(){ try{ items.value=await api('/api/models') }catch(e){error.value=(e as Error).message} }
function open(item?:ModelConfig){ editing.value=item||null; Object.assign(form,item?{...item,api_key:''}:{name:'',provider:'deepseek',model:'deepseek-chat',base_url:'https://api.deepseek.com',api_key:'',enabled:true,temperature:.7,max_tokens:4096});showForm.value=true }
function providerChanged(){ if(form.provider==='qwen'){form.model='qwen-plus';form.base_url='https://dashscope.aliyuncs.com/compatible-mode/v1'}else{form.model='deepseek-chat';form.base_url='https://api.deepseek.com'} }
async function save(){loading.value=true;error.value='';try{const path=editing.value?`/api/models/${editing.value.id}`:'/api/models';await api(path,{method:editing.value?'PUT':'POST',body:JSON.stringify(form)});showForm.value=false;message.value='模型配置已保存';await load()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function remove(item:ModelConfig){if(!confirm(`确定删除“${item.name}”吗？`))return;try{await api(`/api/models/${item.id}`,{method:'DELETE'});await load()}catch(e){error.value=(e as Error).message}}
async function test(item:ModelConfig){message.value='';error.value='';try{const r=await api<{message:string}>(`/api/models/${item.id}/test`,{method:'POST'});message.value=r.message}catch(e){error.value=(e as Error).message}}
onMounted(load)
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">MODEL REGISTRY</div><h1>模型</h1><p class="subtitle">管理 DeepSeek 与阿里云百炼的 OpenAI 兼容配置。</p></div><button class="button button--lime" @click="open()"><Plus :size="15"/>新增模型</button></div>
  <div v-if="message" class="notice"><CheckCircle2 :size="14"/>{{message}}</div><div v-if="error" class="error">{{error}}</div>
  <div class="table-wrap"><table class="data-table"><thead><tr><th>模型配置</th><th>供应商</th><th>模型标识</th><th>密钥</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><div class="primary-cell">{{item.name}}</div><div class="cell-sub">{{item.base_url}}</div></td><td>{{item.provider==='qwen'?'阿里云百炼':'DeepSeek'}}</td><td><code>{{item.model}}</code></td><td>{{item.has_api_key?item.api_key_hint:'未配置'}}</td><td><span class="badge" :class="item.enabled?'badge--ok':''">{{item.enabled?'启用':'停用'}}</span></td><td><div class="row-actions"><button class="icon-button" title="测试连接" @click="test(item)"><RefreshCw :size="14"/></button><button class="icon-button" title="编辑" @click="open(item)"><Pencil :size="14"/></button><button class="icon-button" title="删除" @click="remove(item)"><Trash2 :size="14"/></button></div></td></tr></tbody></table></div>
  <div v-if="showForm" class="modal-backdrop" @click.self="showForm=false"><section class="modal"><header><div><div class="eyebrow">MODEL CONFIG</div><h2>{{editing?'编辑模型':'新增模型'}}</h2></div><button class="icon-button" title="关闭" @click="showForm=false"><X :size="17"/></button></header><form class="form-grid" @submit.prevent="save"><div class="field"><label>配置名称</label><input v-model="form.name" required></div><div class="field"><label>供应商</label><select v-model="form.provider" @change="providerChanged"><option value="deepseek">DeepSeek</option><option value="qwen">阿里云百炼</option></select></div><div class="field"><label>模型标识</label><input v-model="form.model" required></div><div class="field"><label>API Key</label><input v-model="form.api_key" type="password" :placeholder="editing&&editing.has_api_key?'留空保留现有密钥':'请输入 API Key'"></div><div class="field field--full"><label>接口地址</label><input v-model="form.base_url" type="url" required></div><div class="field"><label>温度 {{form.temperature}}</label><input v-model.number="form.temperature" type="range" min="0" max="2" step="0.1"></div><div class="field"><label>最大输出 Token</label><input v-model.number="form.max_tokens" type="number" min="1"></div><div class="field field--full checkline"><input id="model-enabled" v-model="form.enabled" type="checkbox"><label for="model-enabled">启用此模型配置</label></div><div class="field--full actions end"><button type="button" class="button button--secondary" @click="showForm=false">取消</button><button class="button" :disabled="loading">{{loading?'保存中...':'保存配置'}}</button></div></form></section></div>
</template>

