<script setup lang="ts">
import { Activity, ChevronRight, Clock3, X } from 'lucide-vue-next'
import { onMounted, ref } from 'vue'
import { api } from '@/api/client'
import type { RunEvent, RunSummary } from '@/types'
const items=ref<RunSummary[]>([]),events=ref<RunEvent[]>([]),selected=ref<RunSummary|null>(null),error=ref('')
const statusText:Record<string,string>={completed:'已完成',failed:'失败',started:'运行中',interrupted:'已中断'}
async function load(){try{items.value=await api('/api/runs')}catch(e){error.value=(e as Error).message}}
async function inspect(item:RunSummary){selected.value=item;const detail=await api<{events:RunEvent[]}>(`/api/runs/${item.id}`);events.value=detail.events}
function eventName(type:string){const names:Record<string,string>={'run.started':'开始运行','message.delta':'模型输出','message.completed':'回复完成','tool.requested':'请求工具','tool.completed':'工具完成','tool.failed':'工具失败','approval.required':'等待审批','approval.resolved':'审批完成','run.completed':'运行完成','run.failed':'运行失败'};return names[type]||type}
onMounted(load)
</script>
<template><div class="page-heading"><div><div class="eyebrow">RUN AUDIT</div><h1>运行记录</h1><p class="subtitle">查看模型、工具与审批事件的完整时间线。</p></div></div><div v-if="error" class="error">{{error}}</div><div v-if="items.length" class="table-wrap"><table class="data-table"><thead><tr><th>运行标识</th><th>状态</th><th>事件</th><th>开始时间</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id" @click="inspect(item)"><td><div class="primary-cell">{{item.id.slice(0,8)}}</div><div class="cell-sub">会话 {{item.session_id?.slice(0,8)||'—'}}</div></td><td><span class="badge" :class="item.status==='completed'?'badge--ok':item.status==='failed'?'badge--bad':'badge--warn'">{{statusText[item.status]||item.status}}</span></td><td>{{item.event_count}}</td><td>{{new Date(item.started_at).toLocaleString('zh-CN')}}</td><td><ChevronRight :size="15"/></td></tr></tbody></table></div><div v-else class="empty"><div><Activity/><h2>暂无运行记录</h2><p>运行智能体后，事件会显示在这里。</p></div></div><div v-if="selected" class="trace-panel"><header><div><div class="eyebrow">EVENT TRACE</div><h2>{{selected.id}}</h2></div><button class="icon-button" title="关闭" @click="selected=null"><X :size="16"/></button></header><div class="trace"><article v-for="event in events" :key="event.sequence"><span class="trace-index">{{String(event.sequence).padStart(2,'0')}}</span><div><b>{{eventName(event.type)}}</b><small><Clock3 :size="10"/>{{new Date(event.timestamp).toLocaleTimeString('zh-CN')}}</small><pre v-if="Object.keys(event.data).length">{{JSON.stringify(event.data,null,2)}}</pre></div></article></div></div></template>
<style scoped>.data-table tbody tr{cursor:pointer}.trace-panel{position:fixed;right:0;top:0;z-index:45;width:min(560px,100%);height:100vh;background:#f4f5f2;border-left:1px solid var(--line-dark);box-shadow:-12px 0 40px rgba(0,0,0,.12);overflow:auto}.trace-panel>header{position:sticky;top:0;z-index:1;background:white;border-bottom:1px solid var(--line);padding:18px;display:flex;align-items:flex-start;justify-content:space-between}.trace-panel h2{font:12px ui-monospace,monospace;margin:5px 0}.trace{padding:18px}.trace article{display:grid;grid-template-columns:28px 1fr;gap:10px;padding-bottom:15px;position:relative}.trace article:before{content:'';position:absolute;left:13px;top:25px;bottom:0;border-left:1px solid var(--line)}.trace-index{width:27px;height:27px;display:grid;place-items:center;background:var(--ink);color:white;font:9px ui-monospace,monospace}.trace b{font-size:11px}.trace small{display:flex;align-items:center;gap:4px;color:var(--muted);font-size:9px;margin-top:3px}.trace pre{font-size:9px;max-height:170px;margin:7px 0 0}</style>

