<script setup lang="ts">
import { Archive, Boxes, Pencil, Plus, Trash2, Upload, X } from 'lucide-vue-next'
import { onMounted, reactive, ref } from 'vue'
import { api } from '@/api/client'
import SkillTree from '@/components/SkillTree.vue'
import type { Skill } from '@/types'
const items=ref<Skill[]>([]),selected=ref<Skill|null>(null),showForm=ref(false),editing=ref<Skill|null>(null),error=ref(''),query=ref('')
const form=reactive({name:'',description:'',content:'# 技能名称\n\n描述技能的用途和使用方式。',enabled:true})
async function load(){try{items.value=await api('/api/skills')}catch(e){error.value=(e as Error).message}}
async function inspect(item:Skill){try{selected.value=await api(`/api/skills/${item.id}`)}catch(e){error.value=(e as Error).message}}
function open(item?:Skill){editing.value=item||null;if(item){inspect(item).then(()=>Object.assign(form,{name:selected.value!.name,description:selected.value!.description,content:selected.value!.content,enabled:selected.value!.enabled}))}else Object.assign(form,{name:'',description:'',content:'# 技能名称\n\n描述技能的用途和使用方式。',enabled:true});showForm.value=true}
async function save(){try{const path=editing.value?`/api/skills/${editing.value.id}`:'/api/skills';await api(path,{method:editing.value?'PUT':'POST',body:JSON.stringify(form)});showForm.value=false;await load()}catch(e){error.value=(e as Error).message}}
async function toggle(item:Skill){try{await api(`/api/skills/${item.id}`,{method:'PATCH',body:JSON.stringify({enabled:!item.enabled})});await load()}catch(e){error.value=(e as Error).message}}
async function remove(item:Skill){if(!confirm(`确定删除“${item.name}”吗？`))return;try{await api(`/api/skills/${item.id}`,{method:'DELETE'});selected.value=null;await load()}catch(e){error.value=(e as Error).message}}
async function upload(event:Event){const input=event.target as HTMLInputElement;if(!input.files?.[0])return;const body=new FormData();body.append('file',input.files[0]);try{await api('/api/skills/import',{method:'POST',body});await load()}catch(e){error.value=(e as Error).message}finally{input.value=''}}
onMounted(load)
</script>
<template><div class="page-heading"><div><div class="eyebrow">SKILL DIRECTORY</div><h1>技能</h1><p class="subtitle">每个技能都由一个包含 SKILL.md 的本地目录描述。</p></div><div class="actions"><label class="button button--secondary"><Upload :size="14"/>导入 ZIP<input type="file" accept=".zip" hidden @change="upload"></label><button class="button button--lime" @click="open()"><Plus :size="14"/>新建技能</button></div></div><div v-if="error" class="error">{{error}}</div><div class="skill-layout"><section><div class="skill-search"><input v-model="query" placeholder="搜索技能"></div><div class="skill-list"><article v-for="item in items.filter(i=>i.name.includes(query)||i.description.includes(query))" :key="item.id" :class="{active:selected?.id===item.id}" @click="inspect(item)"><span class="skill-icon"><Boxes :size="18"/></span><span><b>{{item.name}}</b><small>{{item.description||'暂无描述'}}</small></span><button class="switch" :class="{on:item.enabled}" :aria-label="`${item.enabled?'停用':'启用'}${item.name}`" @click.stop="toggle(item)"/></article><div v-if="!items.length" class="empty"><div><Archive/><h2>还没有技能</h2><p>创建技能或导入 ZIP 包。</p></div></div></div></section><aside class="panel skill-detail"><template v-if="selected"><div class="panel-header"><div><h2>{{selected.name}}</h2><span class="badge" :class="selected.enabled?'badge--ok':''">{{selected.enabled?'已启用':'已停用'}}</span></div><div class="row-actions"><button class="icon-button" title="编辑" @click="open(selected)"><Pencil :size="14"/></button><button class="icon-button danger-text" title="删除" @click="remove(selected)"><Trash2 :size="14"/></button></div></div><div class="panel-body"><h3>目录结构</h3><SkillTree :nodes="selected.tree||[]"/><h3>SKILL.md</h3><pre>{{selected.content}}</pre></div></template><div v-else class="empty detail-empty"><div><Boxes/><h2>选择一个技能</h2><p>查看目录结构与入口说明。</p></div></div></aside></div><div v-if="showForm" class="modal-backdrop" @click.self="showForm=false"><section class="modal"><header><div><div class="eyebrow">SKILL EDITOR</div><h2>{{editing?'编辑技能':'新建技能'}}</h2></div><button class="icon-button" title="关闭" @click="showForm=false"><X :size="17"/></button></header><form class="form-grid" @submit.prevent="save"><div class="field"><label>技能名称</label><input v-model="form.name" required></div><div class="field"><label>描述</label><input v-model="form.description"></div><div class="field field--full"><label>SKILL.md</label><textarea v-model="form.content" class="code-editor" required></textarea></div><div class="field--full actions end"><button type="button" class="button button--secondary" @click="showForm=false">取消</button><button class="button">保存技能</button></div></form></section></div></template>
<style scoped>.skill-layout{display:grid;grid-template-columns:minmax(380px,.9fr) minmax(400px,1.1fr);gap:16px}.skill-search{margin-bottom:8px}.skill-search input{width:100%;height:38px;border:1px solid var(--line-dark);padding:0 11px;background:white;border-radius:var(--radius);font-size:12px}.skill-list{border:1px solid var(--line);background:white}.skill-list article{min-height:67px;padding:10px 12px;display:grid;grid-template-columns:36px 1fr auto;align-items:center;gap:10px;border-bottom:1px solid var(--line);cursor:pointer}.skill-list article:last-child{border:0}.skill-list article:hover,.skill-list article.active{background:#f1f5ed}.skill-icon{width:34px;height:34px;display:grid;place-items:center;background:#e6eedf}.skill-list b,.skill-list small{display:block}.skill-list b{font-size:12px}.skill-list small{font-size:10px;color:var(--muted);margin-top:3px}.skill-detail{min-height:500px}.skill-detail .panel-header>div:first-child{display:flex;align-items:center;gap:8px}.skill-detail h3{font-size:11px;margin:8px 0;color:var(--muted)}pre{white-space:pre-wrap;max-height:240px;overflow:auto;background:#202622;color:#dce4dd;padding:13px;border-radius:4px;font:10px/1.7 ui-monospace,monospace}.code-editor{min-height:320px!important;font:11px/1.65 ui-monospace,monospace!important}.detail-empty{border:0;min-height:498px}@media(max-width:900px){.skill-layout{grid-template-columns:1fr}.skill-detail{min-height:360px}}
</style>

